name: "checks"

on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        runtime: [osx-arm64]
        include:
          - runtime: osx-arm64
            os: macos-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: cachix/install-nix-action@v22
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.9.0pre20220428_660835d/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix flake check
    - run: nix run nixpkgs#statix -- check ./pkgs && nix run nixpkgs#statix -- check ./modules && nix run nixpkgs#statix -- check flake.nix
    - run: nix run github:astro/deadnix -- -fh ./modules ./pkgs flake.nix
