name: "format"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: cachix/install-nix-action@v22
      with:
        install_url: https://github.com/nix-community/nix-unstable-installer/releases/download/nix-2.17.0pre20230630_d05d175/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix fmt -- --check ./
